sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "node"

script: npm run-script coverage && (npm run-script coveralls || exit 0)

before_script:
  - npm i git+https://git@github.com/physikerwelt/mathoid-server.git
  - cd node_modules/mathoid
  - chmod +x server.js
  - ./server.js -c ../../config.dev.yaml &
  - cd ../..
