sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "node"

script: npm run-script coverage && (npm run-script coveralls || exit 0)

before_script:
  - npm i mathoid@dev
  - cd node_modules/mathoid
  - ./server.js -c ../../config.dev.yaml &
  - cd ../..
